import { describe, expect, it } from 'vitest';

import {
  createRuntimeEnvironment,
  createTotpSecret,
  createTotpUri,
  encodeBase32,
  validAdminPassword,
} from '../src/helpers.js';

describe('admin CLI helpers', () => {
  it('requires an administrator password of at least ten characters', () => {
    expect(validAdminPassword('123456789')).toBe(false);
    expect(validAdminPassword('1234567890')).toBe(true);
  });

  it('encodes RFC 4648 base32 without padding', () => {
    expect(encodeBase32(new TextEncoder().encode('foobar'))).toBe('MZXW6YTBOI');
  });

  it('creates a schema-compatible TOTP secret and URI', () => {
    const secret = createTotpSecret();
    const uri = createTotpUri('admin', secret);

    expect(secret).toMatch(/^[A-Z2-7]{32}$/);
    expect(uri).toContain('otpauth://totp/ModelNaru%3Aadmin?');
    expect(uri).toContain(`secret=${secret}`);
  });

  it('renders a non-secret Compose environment file', () => {
    expect(createRuntimeEnvironment('127.0.0.1', 32432)).toBe(
      '# Generated by apichat-admin. Do not edit by hand.\n' +
        'APICHAT_HOST=127.0.0.1\n' +
        'APICHAT_PORT=32432\n' +
        'APICHAT_UID=1000\n' +
        'APICHAT_GID=1000\n',
    );
  });
});
