import { randomBytes } from 'node:crypto';

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

export function validAdminPassword(value: string): boolean {
  return value.length >= 10;
}

export function encodeBase32(input: Uint8Array): string {
  let bits = 0;
  let value = 0;
  let output = '';

  for (const byte of input) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      output += BASE32_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }

  if (bits > 0) {
    output += BASE32_ALPHABET[(value << (5 - bits)) & 31];
  }

  return output;
}

export function createTotpSecret(): string {
  return encodeBase32(randomBytes(20));
}

export function createTotpUri(username: string, secret: string): string {
  const issuer = 'ModelNaru';
  const label = encodeURIComponent(`${issuer}:${username}`);
  const parameters = new URLSearchParams({
    algorithm: 'SHA1',
    digits: '6',
    issuer,
    period: '30',
    secret,
  });
  return `otpauth://totp/${label}?${parameters.toString()}`;
}

export function createRuntimeEnvironment(
  host: string,
  port: number,
  uid = '1000',
  gid = '1000',
): string {
  if (!/^\d+$/.test(uid) || !/^\d+$/.test(gid)) {
    throw new Error('APICHAT_UID and APICHAT_GID must be numeric');
  }

  return [
    '# Generated by apichat-admin. Do not edit by hand.',
    `APICHAT_HOST=${host}`,
    `APICHAT_PORT=${port}`,
    `APICHAT_UID=${uid}`,
    `APICHAT_GID=${gid}`,
    '',
  ].join('\n');
}
